name: HCore
version: "10.4.2"
main: ru.dehasher.hcore.bukkit.HCore
api-version: 1.13

author: deHasher
website: https://dehasher.ru/

softdepend:
    - FastAsyncWorldEdit
    - PlaceholderAPI
    - UltimateTimber
    - LibsDisguises
    - ChunkyBorder
    - WorldBorder
    - ProtocolLib
    - GadgetsMenu
    - WorldGuard
    - ajParkour
    - WorldEdit
    - LuckPerms
    - ItemJoin
    - LiteBans
    - Spark
    - Vault
    - TAB
    - CMI

# Список возможностей, команд, разрешений и заполнителей можно посмотреть тут: https://github.com/deHasher/HCore
